### ISSUE TITLE
Activate or deactivate checks with configuration

### ISSUE THREAD

**Issue by brunobat** [smallrye/smallrye-health#128]
We are creating an internal lib with custom liveness and readiness checks. 
It would be very handy if we could activate or deactivate individual checks as needed on particular microservices, where we will use that lib. 
Can you please add a property like:
`com.mypackage.healthcheck.RabbitMqReadyCheck.enabled=false`
They should be enabled by default. 
Can you please add this behaviour?

**Comment by xstefank** [comment]
I think this is an interesting idea.
