### ISSUE TITLE
Kubernetes Startup Probe

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-health#165]
Similar to Readiness and Liveness, Kubernetes is introducing a "Startup Probe" to assist in situations where the startup of an application can be a longer period than "liveness". During startup, it disables readiness and liveness probes to prevent premature killing of a container.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

Would be worth doing some innovation around adding such a probe to SmallRye and then Quarkus

**Comment by cescoffier** [comment]
It's not only this, they changed the readiness semantic. Readiness can now be called while receiving traffic, which means it must be implemented in a non-expensive/non-disruptive way. Typically, while before you could do expensive I/O in the readiness probe, it should not be the case anymore. 

We used readiness as a startup probe.

**Comment by cescoffier** [comment]
Note: having support for startup and this new readiness is important for reactive messaging, as now, we can imagine stopping the polling of messages because we have too many inflight messages.

**Comment by Ladicek** [comment]
> Readiness can now be called while receiving traffic

Care to elaborate? To the best of my understanding, it was always the case that readiness probes were called during the entire life of application.

**Comment by cescoffier** [comment]
So my bad. Pretty sure that's something I checked and it was not called after being ready. 
Anyway, many of our implementations do expensive operations during the readiness check, which should not be done. Typically, the kafka connector checks the existence of topics - which lead to interacting with the broker. I should only be done a startup time.

**Comment by xstefank** [comment]
So this would be another type of the predefined group of checks. I think this has its place now in the spec as we are directly mentioning Kubernetes probes. I will introduce this in SR so it can be tested for a release or two in quarkus and we can push it in the next spec version sometime next year.

**Comment by cescoffier** [comment]
+1
