### ISSUE TITLE
Static access to SmallRyeHealthReporter or HealthRegistry

### ISSUE THREAD

**Issue by slaskawi** [smallrye/smallrye-health#172]
## Feature Request

Currently, it is pretty hard to wire new `HealthCheck` implementation into the `SmallRyeHealthReporter` in a non-CDI environment. Moreover, assembling `SmallRyeHealthReporter` by hand (without CDI) seems to be non-trivial. I would like to request more support for accessing those classes from the static context.

## More context

When working on Observability and Healthcheck API concepts for Keycloak, I found it very convenient that `MetricRegistries` class has static accessors (`MetricRegistries#get1). This feature makes wiring into the application code much simpler. It would be great to have something similar in this project.

**Comment by kenfinnigan** [comment]
@antoinesd @xstefank @jmartisk @radcortez anyone free to take a look at this?

**Comment by antoinesd** [comment]
I'm already looking at it @kenfinnigan

**Comment by xstefank** [comment]
thanks @antoinesd

**Comment by slaskawi** [comment]
Thank you!

**Comment by jamesnetherton** [comment]
Any progress on this?

**Comment by xstefank** [comment]
actually today I started working on the 3.2.0 release so hopefully should be coming up soon. Sorry for the delays.

**Comment by xstefank** [comment]
@jamesnetherton @slaskawi the PR is up, can you check please? The reporter will be usable like this - https://github.com/xstefank/learning-tests/blob/master/sr-health-plain/src/main/java/io/xstefank/App.java

**Comment by jamesnetherton** [comment]
> @jamesnetherton @slaskawi the PR is up, can you check please? The reporter will be usable like this - https://github.com/xstefank/learning-tests/blob/master/sr-health-plain/src/main/java/io/xstefank/App.java

LGMT :+1:
