### ISSUE TITLE
Only one additionalCheck per Type allowed in SmallRyeHealthReporter?

### ISSUE THREAD

**Issue by garyhodgson** [smallrye/smallrye-health#193]
Hi - I can't work out the logic behind the addHealthCheck Method of SmallRyeHealthReporter. It seems that only one instance of a healthcheck type is allowed?

https://github.com/smallrye/smallrye-health/blob/18a863d93c6e7df6874d974c209bdd284a9bd263/implementation/src/main/java/io/smallrye/health/SmallRyeHealthReporter.java#L420

e.g. when I call it with:

```
        smallRyeHealthReporter.addHealthCheck(new UrlHealthCheck("http://google.com"));
        smallRyeHealthReporter.addHealthCheck(new UrlHealthCheck("http://bing.com"));
```
then only the last check appears.

**Comment by xstefank** [comment]
Hi, this is a more or less deprecated API that we mostly use in testing that was replaced with the experimental registry feature. With that you can do:

```java
@Startup
public class StartupBean {

    public StartupBean(@Liveness HealthRegistry hr) {
        hr.register("google", new UrlHealthCheck("http://google.com"));
        hr.register("bing", new UrlHealthCheck("http://bing.com"));
    }
}
```

**Comment by garyhodgson** [comment]
Hi - my apologies! I totally forgot to close the issue!  The register feature appears to work fine and do as I need, thanks!

**Comment by xstefank** [comment]
No worries. Thank you for trying it out.
