### ISSUE TITLE
Add extra fields on the same level with status field

### ISSUE THREAD

**Issue by StanislavMakhrov** [smallrye/smallrye-health#343]
Hi!

Is it possible to add to healthcheck custom fields on the same level with status field?

I want something like:
```
{
    "status": "UP",
    "appVersion": "1.0.0-ci.234",
    "branch": "master",
    "owner": "John Doe",
    "checks": [ ]
}
```

So, I have added extra fields appVersion, branch and owner. I need this in healthcheck. How can I add this in code? Or does it requires changes in smallrye-health?

**Comment by xstefank** [comment]
Hi @StanislavMakhrov. This is not currently possible to be done directly in the HealthChecks. However, there is an easy possibility to extend this yourself (workaround basically) - https://github.com/xstefank/learning-tests/blob/master/sr-health-custom-top-level-fields/src/main/java/io/xstefank/CustomHC.java. 

If we would implement this in SR, would you like these values to be dynamic or can they be specified in the config values?

**Comment by SMakhrov** [comment]
Nice example! Thanks! I think it should be in healthcheck out of the box.
I get these values from build.properties file using class with @ConfigMapping annotation.

Regarding nice example above. I can't do this in reactive way because such code causes error:
```
import com.aligntech.cs.treatcanaryapi.config.BuildInfoProperties;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import io.smallrye.health.SmallRyeHealthReporter;
import io.smallrye.mutiny.Uni;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

@Path("/healthcheck")
@ApplicationScoped
public class HealthCheckController {

    @Inject
    BuildInfoProperties buildInfoProperties;

    @Inject
    SmallRyeHealthReporter smallRyeHealthReporter;

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Uni<Response> reportHealth() throws JsonProcessingException {
        return Uni.createFrom().item(Response.ok(
                new ObjectMapper().readValue(smallRyeHealthReporter.getHealth()
                        .getPayload().toString(), ObjectNode.class)
                        .put("appVersion", buildInfoProperties.appVersion())
                        .put("revision", buildInfoProperties.revision())
                        .put("branch", buildInfoProperties.scmBranch())).build());
    }
}
```

Error:
Internal Server Error
Error id 4290e94c-ec27-43a8-ae34-5ecfe7461f22-1, java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-9

**Comment by xstefank** [comment]
We have also async support in SR health so to do the workaround the reactive way you can try this - https://github.com/xstefank/learning-tests/blob/master/sr-health-custom-top-level-fields-reactive/src/main/java/io/xstefank/CustomHC.java. 

I see no problem in adding this then as a feature that will read the values that should be added at the top level from the config directly. Thanks.

**Comment by SMakhrov** [comment]
@xstefank thanks again! It works perfect!
One question: how can I disable standard healthcheck /q/health
Because now I have two healthchecks - by url /q/health and my custom url.

This doesn't work for me:
```
quarkus:
  health:
    extensions:
      enabled: false
```

**Comment by xstefank** [comment]
@SMakhrov this property will only disable any health checks that are exposed in different Quarkus extensions. There is no way to disable the /q/health endpoint. You can only use path configs to move it somewhere else - https://quarkus.io/guides/smallrye-health#quarkus-smallrye-health_configuration. But I will work on this feature in SR so there should not be a need for this hopefully soon.

**Comment by SMakhrov** [comment]
Thank you so much!

@xstefank if I want to add some check (for example DB connection), how can I do this?
I've used this example https://github.com/xstefank/learning-tests/blob/master/sr-health-custom-top-level-fields-reactive/src/main/java/io/xstefank/CustomHC.java and tried to do something like:

```
    @GET
    @Path("/health")
    public Uni<Response> reportHealth() throws JsonProcessingException {
        HealthCheckResponse.named("Database").down().build();
        return smallRyeHealthReporter.getHealthAsync().onItem().transform(health -> {
            ObjectMapper objectMapper = new ObjectMapper();

            ObjectNode objectNode = null;
            try {
                objectNode = objectMapper.readValue(health.getPayload().toString(), ObjectNode.class);
            } catch (JsonProcessingException e) {
                e.printStackTrace();
            }
            objectNode.put("customKey", "customValue");

            return Response.ok(objectNode).build();
        });

    }
```
I've added this string according example above:
```
HealthCheckResponse.named("Database").down().build();
```
But I don't see Database in output JSON;

I've awaited that overall healthcheck would pay attention that DB is DOWN then overall status also will be DOWN.

**Comment by xstefank** [comment]
@StanislavMakhrov for that you need to define the HealthCheck (or AsyncHealthCheck) normally as you used to - https://github.com/xstefank/learning-tests/blob/master/sr-health-custom-top-level-fields-reactive/src/main/java/io/xstefank/NormalHC.java. ``smallRyeHealthReporter.getHealthAsync()` is what is called when you access normal health endpoint (/q/health) and will process all HealthChecks beans normally.
