### ISSUE TITLE
Add experimental wellness Health Check procedures

### ISSUE THREAD

**Issue by antoinesd** [smallrye/smallrye-health#41]
We need to introduce the support for `/health/wellness` and `@Wellness` qualifier

**Comment by Ladicek** [comment]
I think similarly to `@Liveness` having `/health/live` and `@Readiness` having `/health/ready`, `@Wellness` should have `/health/well`.

**Comment by xstefank** [comment]
@Ladicek it might be, but `well` as a word is quite overloaded :) I personally don't have preference.

**Comment by xstefank** [comment]
@antoinesd do we want to introduce this as experimental or wait for the spec (there are no comments in GG).

**Comment by antoinesd** [comment]
I think we can wait to have it in the spec. Wdyt?

**Comment by kenfinnigan** [comment]
We need to be validating ideas in the implementation before we bring them to the spec

**Comment by xstefank** [comment]
@kenfinnigan do you mean that we shouldn't now add any new API in the spec if it hasn't been already for some time in SR?

**Comment by kenfinnigan** [comment]
That has been the understanding for a while and made as clear as I and others can over the last 4-5 months.

**Comment by xstefank** [comment]
yeah, I know but given the timeline, we won't introduce any new features in Health 3.0 if we take this into account, unfortunately. While we still need a breaking release this seems a little harsh trade-off for users.

**Comment by kenfinnigan** [comment]
Maybe, but that's the approach we're taking.

If we haven't proven that a new API is usable, appropriate, and defined properly, it's premature to add it to a spec
