### ISSUE TITLE
Registry for HealthGroups

### ISSUE THREAD

**Issue by HerrDerb** [smallrye/smallrye-health#414]
We have a library containing a common HealthCheck.
We do use this library now for an application and would love to have this provided health check in an application specific group.

We now did a dirty workaround and added the desired health group in the library. This kind of mixes contexts.

Refering to the Note : https://smallrye.io/docs/smallrye-health/3.0.1/health-registry.html, it would be nice if there would be a possibility to register a health check to certain group programmatically. This way I can configure any existing Healthcheck, self implemented or provided, for a certain health group.

**Comment by xstefank** [comment]
Hi @HerrDerb, actually sorry, the docs are long on my TODO list to update.

This is already possible to do like this:

```
HealthRegistry myHealthGroup = HealthRegistries.getHealthGroupRegistry("my-health-group");
myHealthGroup.register(() -> HealthCheckResponse.up("test-hc"));
```

Also please note that custom health group needs to be defined in Quarkus prior the deployment for now - https://github.com/smallrye/smallrye-health/issues/397. I will fix this in next SR Health upgrade in quarkus.

**Comment by HerrDerb** [comment]
Oh cool, I'll try that then. 👍

**Comment by HerrDerb** [comment]
Already available
