### ISSUE TITLE
Default HealthGroup when not defined

### ISSUE THREAD

**Issue by xstefank** [smallrye/smallrye-health#425]
Originally proposed in https://github.com/quarkusio/quarkus/issues/26877.

**Comment by HerrDerb** [comment]
Any progress on this on? 🙂

**Comment by xstefank** [comment]
sorry @HerrDerb I will do the release next week. Baffled with other stuff :(.

**Comment by HerrDerb** [comment]
@xstefank 👍 no hurry, I just wasn't sure if the issue has gone out of sight :)
