### ISSUE TITLE
Investigate how to handle concurrency correctly

### ISSUE THREAD

**Issue by xstefank** [smallrye/smallrye-health#488]
A follow up to https://github.com/smallrye/smallrye-health/pull/486

**Comment by xstefank** [comment]
Thanks @HerrDerb. I agree. If you would like to create a PR please do. If not, I can fix this but it would be useful if we could have a reproducer.

**Comment by HerrDerb** [comment]
I've a got a proposal here: https://github.com/smallrye/smallrye-health/pull/508

**Comment by xstefank** [comment]
For now I'm resolving this as part of #508
