### ISSUE TITLE
Unable to compile on Java 11-ea+25, TCK module fails with ModuleNotFoundException: java.se

### ISSUE THREAD

**Issue by rsvoboda** [smallrye/smallrye-health#5]
Unable to compile on Java 11-ea+25, TCK module fails with ModuleNotFoundException: java.se

```
org.jboss.modules.ModuleNotFoundException: java.se
	at org.jboss.modules.Module.addPaths(Module.java:1266)
	at org.jboss.modules.Module.link(Module.java:1622)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1650)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:296)
	at org.jboss.modules.Main.main(Main.java:437)
[ERROR] Tests run: 22, Failures: 1, Errors: 0, Skipped: 21, Time elapsed: 1.208 s <<< FAILURE! - in TestSuite
[ERROR] arquillianBeforeSuite(org.eclipse.microprofile.health.tck.MultipleProceduresFailedTest)  Time elapsed: 1.072 s  <<< FAILURE!
org.jboss.arquillian.container.spi.client.container.LifecycleException: The java process starting the managed server exited unexpectedly with code [1]
```

This issue is related to https://issues.jboss.org/browse/WFCORE-3962
`--add-modules=java.se` needs to be added when running on Java 11 ea

Seems there is no easy fix on JBoss Modules side, @dmlloyd tried few things but we are still stuck with `--add-modules=java.se` workaround

I tried to look here and in https://github.com/eclipse/microprofile-health but I wasn't successful to find place where the workaround could be added - no dedicated jdk9+ profile or arquillian.xml

**Comment by kenfinnigan** [comment]
Current MicroProfile is only expected to work on JDK 8, no testing has been done with more recent JDK versions.

Once JDK 11 is out I expect there will need to be some work across all the specs for that

**Comment by kenfinnigan** [comment]
Resolved
