### ISSUE TITLE
Create a HealthStatus helper class

### ISSUE THREAD

**Issue by lordofthejars** [smallrye/smallrye-health#50]
Checking MicroProfile spec, in CDI section (https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/java-api.adoc#integration-with-cdi) you'll see that they are using a class called HealthStatus. This class is not a spec class but a helper class created for the sake of simplifying the example.

But after using the spec a bit, I have arrived at the conclusion that a simple helper class for basic usage is more beneficial than having to deal with the builder all the time, for this reason, I implemented this simple class in Health extension to improve the developer experience.

PR is coming.

**Comment by xstefank** [comment]
@lordofthejars there is already a similar proposal in the spec - https://github.com/eclipse/microprofile-health/issues/184. Would that cover what you request? Looking at examples in CDI section, keep in mind please that health checks must have names.

**Comment by lordofthejars** [comment]
Yes it is something similar, but not identical because the `HealthStatus` approach takes care of the boolean decision too so developers skip the phase of:

```
if (ok) then .up else .down
```

**Comment by xstefank** [comment]
@lordofthejars isn't that covered by this method - https://github.com/eclipse/microprofile-health/blob/master/api/src/main/java/org/eclipse/microprofile/health/HealthCheckResponseBuilder.java#L46 ?

**Comment by lordofthejars** [comment]
Partially yes, my idea is to provide the method that you can set as parameter a `BooleanSupplier`, so you are not tight only to `boolean` type. Also will provide directly a `HealthCheck` object to be used directly by CDI instead of having to do the `.build` and then create the anonymous class.

So in CDI without this helper class could be:

```
@Produces
@ApplicationScoped
// ...
public HealthCheck check() {
  boolean state = checkForState();
  HealthCheckResponse healthCheck = HCRB.name("xxx").state(state).build();
  return () -> healthCheck;
}
```

Now with helper method:

````
return HealthStatus.state("xxx", check())
```

So all this anonymous class and dealing with builder is encapsulated.

**Comment by xstefank** [comment]
Exactly, I am thinking about how much of this can be pushed up to the spec. Go ahead and create PR, please.

**Comment by lordofthejars** [comment]
Yes, I think that everything could be pushed into the spec, but let's start with the PR, we can discuss there, maybe even merge and then let's move discussion forward to spec.
