### ISSUE TITLE
Add default implementations of HealthCheck

### ISSUE THREAD

**Issue by lordofthejars** [smallrye/smallrye-health#53]
I was thinking that we could provide some implementations of `HealthCheck` interface to be used by our users which are typical use cases. I was thinking:

* IP check ( aka `ping`)
* URL check (check if it returns a 200 OK)
* Execute SQL query and validate it returns a result (hard to implement but maybe if we integrate with JPA it might be easy)

So any service can use these to validate that any dependency that they require to be up and running are met.

We could even provide some checks for specifically to RH products like OpenShift (pod is up and running), Infinispan (migration has been finished), ...

**Comment by kenfinnigan** [comment]
Not sure TBH. I can see benefits but also drawbacks.

Though it might be nice to include some OOTB health checks, I wouldn't want to impede how their enabled/disabled in runtimes. See https://github.com/quarkusio/quarkus/issues/3107

And I don't think we'd want to start adding dependencies just to create health checks

**Comment by lordofthejars** [comment]
Well my idea is to create just as anu helper class and the developer is the
responsible of instantiating them as we do in healthstatus class

**Comment by kenfinnigan** [comment]
Would that just be more cumbersome?

If we created health checks that were just methods that returned a `HealthCheckResponse`, implementors would still need to create the Bean that produced the outcome for the runtime.

Given the possible configuration that would be required to make the health checks flexible enough for use in different runtimes, does it provide much benefit?

Maybe if you propose a PR with some of what you're thinking it might be easier to evaluate?

**Comment by lordofthejars** [comment]
Ok I'll do this so you can see how it should work.

**Comment by lordofthejars** [comment]
@kenfinnigan The PR is here https://github.com/smallrye/smallrye-health/pull/54 you can see in JavaDoc how to use it. It is just an idea, so we can discuss, discard, change, ...
