### ISSUE TITLE
/health not on management port

### ISSUE THREAD

**Issue by gabrielJoergArz** [smallrye/smallrye-health#68]
Hi!

Would it be possible to not publish the /health ressources on the management port, but on some different (maybe http/s) port?

Why did you implement it that way anyways?

Background: Like that it isn't well usable on platforms like kubernetes, because you would have to open up your management port completely, and even then it can be difficult for kubernetes to connect to it, if it doesn't do it from the same "machine".

**Comment by kenfinnigan** [comment]
I don't believe there's anything in SmallRye Health that ties where the endpoint is available.

It's up to the runtime that uses SmallRye Health to define where it's accessible.

**Comment by Ladicek** [comment]
Considering you mention the management port, I guess you use SmallRye Health via WildFly? (Quarkus doesn't have a management port, and Thorntail exposes health on the main port.) If so, I think this issue belongs to the WildFly issue tracker.

**Comment by gabrielJoergArz** [comment]
Okay I'm sorry, yes we are using wildfly (18).

So you think there might be an option to configure it?

**Comment by kenfinnigan** [comment]
Possibly, you'd need to check with them

**Comment by gabrielJoergArz** [comment]
K thanks for clearing that up!
