### ISSUE TITLE
Cannot set emptyChecksOutcome in thorntail 

### ISSUE THREAD

**Issue by filippobuletto** [smallrye/smallrye-health#84]
I’m trying to set the property `io.smallrye.health.emptyChecksOutcome` Using latest thorntail build, I’ve tried to set the DOWN value using the properties file and also using the environment variable but still when the “internal wildfly” have booted but the war is still deploying the health endpoint returns an UP status (which triggers traffic being sent to the service with obvious erratic traffic).
Am I missing something? Thanks

**Comment by xstefank** [comment]
I believe this is the wrong behavior of Thorntail which can return a hardcoded health check response - https://github.com/thorntail/thorntail/blob/master/fractions/microprofile/microprofile-health/src/main/java/org/wildfly/swarm/microprofile/health/runtime/HttpContexts.java#L124. I raised https://issues.redhat.com/browse/THORN-2535 to track it. This issue can be closed if you agree @filippobuletto.

**Comment by filippobuletto** [comment]
It’s ok for me, thanks!
