### ISSUE TITLE
Performance cost of Json

### ISSUE THREAD

**Issue by loicmathieu** [smallrye/smallrye-health#91]
Currently, SmallRyeHealthReporter use the `javax.json.Json` helper class to create the various Json builder/factory that it needs (JsonArrayBuilder, JsonObjectBuilder, JsonWriterFactory).

This class calls `JsonProvider.provider()` without caching it (the JavaDoc of JsonProvider say that it's safe to cache it) each time it creates a new Json builder/factory.
As `JsonProvider.provider()` uses a ServiceLoader to load the Json implementation, this is a very costly operation.

If the code is updated to cache an instance of JsonProvider and to use this instance to create the various Json object instead of using the Json helper class this performance cost should disapear.

**Comment by geoand** [comment]
:+1: for what @loicmathieu says

**Comment by gsmet** [comment]
@loicmathieu I would say you can prepare a PR for it.

It would be nice to have that in Quarkus 1.5.

**Comment by geoand** [comment]
Yeah, it would be great to have a smallrye health release out that we can pick up for Quarkus 1.5

**Comment by loicmathieu** [comment]
@gsmet OK, I'll send a PR today or tomorrow

**Comment by jmartisk** [comment]
@antoinesd if you don't mind I'll take care of releasing 2.2.1 with this fix and upgrading Quarkus. Do you have something else that you want to include in 2.2.1?

**Comment by gsmet** [comment]
If we just have that one fix in 2.2.1, I could be convinced to backport it to 1.4.2.

**Comment by antoinesd** [comment]
@jmartisk I can do the release. I don't think we have other feature for a 2.2.1
