### ISSUE TITLE
Implement i18n logging and messages

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-health#95]
Follow the procedures defined in https://github.com/smallrye/smallrye-parent/wiki/I18N-Messages-and-Logging as part of implementing https://github.com/smallrye/smallrye-parent/issues/102 for all SmallRye projects

An example usage can be found in https://github.com/smallrye/smallrye-common

**Comment by ejba** [comment]
Hi, can I pick this one? :)

**Comment by kenfinnigan** [comment]
Sure, thanks for taking it on!

**Comment by ejba** [comment]
Hi @kenfinnigan, 
I don't know if it's relevant but I forgot to link the PR ( #96 ) with this issue.

**Comment by xstefank** [comment]
I believe this is resolved. Feel free to reopen if needed.
